import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCircleCheck, faPlus, faCircleNotch } from '@fortawesome/free-solid-svg-icons'
import { faClock } from '@fortawesome/free-regular-svg-icons'

export default function Home() {
  const [tasks, setTasks] = useState([
    {
      "id": 40,
      "descricao": "Escrever relatório de vendas.",
      "prazo": "2016-08-29T09:12:33.001Z",
      "completa": true
    },
    {
      "id": 85,
      "descricao": "Fazer apresentacao do trablaho.",
      "prazo": "2021-04-03T09:12:33.001Z",
      "completa": false
    }
  ]);
  const [isLoaded, setIsLoaded] = useState(false);

  function formatDate(strDate) {
    const date = new Date(strDate);
    return date.toLocaleDateString() + " às " + date.toLocaleTimeString();
  }

  useEffect(() => {
    setInterval(function () {
      setIsLoaded(true);
    }, 1000);
    //   fetch("https://virtserver.swaggerhub.com/neumar/Tarefas/1.0.0/tarefas")
    //     .then(res => res.json())
    //     .then(
    //       (data) => {
    //         setIsLoaded(true);
    //         setTasks(data);
    //       },
    //       (error) => {
    //         setIsLoaded(true);
    //       }
    //     )
  });

  if (!isLoaded) {
    return (
      <div className={styles.container}>
        <div className={styles.loading}>
          <FontAwesomeIcon icon={faCircleNotch} spin={true} style={{ animationDuration: "1.4s" }} />
          <p>Carregando</p>
        </div>
      </div>
    )
  } else {
    return (
      <div className={styles.container}>
        <Head>
          <title>Tarefas</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            <span>Tarefas</span>
            <button className={styles.addButton} type="button">
              <FontAwesomeIcon icon={faPlus} />
            </button>
          </h1>

          <div className={styles.grid}>
            {tasks.map(task => (
              <a href="#" className={styles.card}>
                <h2>{task.descricao} &rarr;</h2>
                {task.completa ?
                  <p><FontAwesomeIcon className={styles.greenText} icon={faCircleCheck} /> Tarefa concluída</p>
                  : <p><FontAwesomeIcon className={styles.yellowText} icon={faClock} /> {`Concluir até o dia ${formatDate(task.prazo)}`}</p>
                }
              </a>
            ))}
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Feito por&nbsp;<strong>João Vitor e Pedro Henrique</strong>
          </a>
        </footer>
      </div>
    )
  }
}
